'use client'

import Link from 'next/link'
import { useState } from 'react'
import { Bell, Check, ChevronRight, CirclePlay, Info, Menu, Play, Plus, Search, Star, User, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import type { Movie } from '@/lib/mock-data'
import { cn } from '@/lib/utils'

export function Logo() { return <Link href="/" className="flex items-center gap-2 text-lg font-bold tracking-tight"><span className="grid size-7 place-items-center rounded-lg bg-primary text-primary-foreground"><Play className="size-3.5 fill-current" /></span><span>stream<span className="text-primary">flix</span></span></Link> }

export function Navbar() {
  const [open, setOpen] = useState(false)
  const links = [['Home', '/'], ['Browse', '/browse'], ['My List', '/my-list']]
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/5 bg-background/80 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex">{links.map(([label, href]) => <Link key={href} href={href} className="transition-colors hover:text-foreground">{label}</Link>)}<Link href="/search" className="transition-colors hover:text-foreground">Search</Link></nav><div className="flex items-center gap-3"><Link href="/search" aria-label="Search" className="rounded-full p-2 text-muted-foreground hover:bg-white/5 hover:text-foreground"><Search className="size-4" /></Link><button aria-label="Notifications" className="hidden rounded-full p-2 text-muted-foreground hover:bg-white/5 hover:text-foreground sm:block"><Bell className="size-4" /></button><Link href="/profile" className="grid size-8 place-items-center overflow-hidden rounded-full bg-gradient-to-br from-primary to-orange-300 text-xs font-bold text-background">JD</Link><button onClick={() => setOpen(!open)} className="rounded-lg p-2 md:hidden" aria-label="Toggle menu">{open ? <X className="size-5" /> : <Menu className="size-5" />}</button></div></div>{open && <nav className="flex flex-col gap-1 border-t border-white/5 bg-background px-5 py-4 md:hidden">{links.concat([['Search', '/search']]).map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)} className="rounded-lg px-3 py-3 text-sm text-muted-foreground hover:bg-white/5 hover:text-foreground">{label}</Link>)}</nav>}</header>
}

export function MovieCard({ movie, landscape = false }: { movie: Movie; landscape?: boolean }) {
  return <Link href={`/movies/${movie.id}`} className={cn('group block min-w-[150px] sm:min-w-[180px]', landscape && 'min-w-[250px] sm:min-w-[300px]')}><div className={cn('relative aspect-[2/3] overflow-hidden rounded-xl bg-card', landscape && 'aspect-video')}><img src={movie.poster} alt={`${movie.title} poster`} className="size-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 transition group-hover:opacity-100" />{movie.progress ? <div className="absolute inset-x-0 bottom-0 h-1 bg-white/20"><div className="h-full bg-primary" style={{ width: `${movie.progress}%` }} /></div> : null}<div className="absolute bottom-3 left-3 right-3 flex translate-y-2 items-center justify-between opacity-0 transition group-hover:translate-y-0 group-hover:opacity-100"><span className="grid size-8 place-items-center rounded-full bg-white text-black"><Play className="size-3.5 fill-current" /></span><span className="text-xs font-medium text-white">{movie.rating}</span></div></div><div className="mt-3"><p className="truncate text-sm font-semibold">{movie.title}</p><p className="mt-1 text-xs text-muted-foreground">{movie.year} <span className="mx-1 text-white/20">•</span> {movie.genre}</p></div></Link>
}

export function MovieRow({ title, movies, action = true }: { title: string; movies: Movie[]; action?: boolean }) { return <section className="space-y-4"><div className="flex items-end justify-between"><h2 className="text-lg font-semibold tracking-tight sm:text-xl">{title}</h2>{action && <Link href="/browse" className="flex items-center gap-1 text-xs font-medium text-muted-foreground hover:text-primary">View all <ChevronRight className="size-3" /></Link>}</div><div className="flex gap-4 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{movies.map((movie) => <MovieCard key={movie.id} movie={movie} />)}</div></section> }

export function Hero({ movie }: { movie: Movie }) { return <section className="relative min-h-[600px] overflow-hidden pt-16"><img src={movie.backdrop} alt="" className="absolute inset-0 size-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-background via-background/75 to-transparent" /><div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-background/10" /><div className="relative mx-auto flex min-h-[540px] max-w-7xl items-end px-5 pb-20 lg:px-8"><div className="max-w-xl"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.24em] text-primary">StreamFlix Original</p><h1 className="text-5xl font-semibold tracking-[-0.06em] text-white sm:text-7xl">{movie.title}</h1><p className="mt-4 text-lg font-medium text-white/80">{movie.tagline}</p><p className="mt-4 max-w-lg text-sm leading-6 text-muted-foreground">{movie.description}</p><div className="mt-5 flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><span className="rounded border border-white/20 px-2 py-1 text-white">{movie.maturity}</span><span>{movie.year}</span><span>{movie.duration}</span><span className="flex items-center gap-1 text-white"><Star className="size-3 fill-primary text-primary" /> {movie.rating}</span></div><div className="mt-7 flex gap-3"><Button asChild className="rounded-full px-5"><Link href={`/movies/${movie.id}`}><Play data-icon="inline-start" className="fill-current" /> Watch now</Link></Button><Button asChild variant="secondary" className="rounded-full bg-white/10 px-5 text-white hover:bg-white/15"><Link href={`/movies/${movie.id}`}><Info data-icon="inline-start" /> More info</Link></Button></div></div></div></section> }

export function ProgressCard({ movie }: { movie: Movie }) { return <Link href={`/movies/${movie.id}`} className="group flex min-w-[280px] gap-4 rounded-xl border border-white/8 bg-card/60 p-3 transition hover:bg-card"><div className="relative aspect-video w-36 shrink-0 overflow-hidden rounded-lg"><img src={movie.poster} alt="" className="size-full object-cover" /><span className="absolute inset-0 grid place-items-center bg-black/30 opacity-0 transition group-hover:opacity-100"><CirclePlay className="size-8 fill-white text-black" /></span></div><div className="flex min-w-0 flex-1 flex-col justify-between py-1"><div><p className="truncate text-sm font-semibold">{movie.title}</p><p className="mt-1 text-xs text-muted-foreground">S1 E4 · 42 min left</p></div><div><div className="mb-2 flex justify-between text-[10px] text-muted-foreground"><span>{movie.progress}% watched</span><span>Resume</span></div><div className="h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-primary" style={{ width: `${movie.progress}%` }} /></div></div></div></Link> }

export function PageShell({ children }: { children: React.ReactNode }) { return <><Navbar /><main className="mx-auto min-h-screen max-w-7xl px-5 pb-24 pt-28 lg:px-8">{children}</main></> }

export function AuthCard({ register = false }: { register?: boolean }) { return <main className="grid min-h-screen place-items-center bg-[radial-gradient(circle_at_top_right,rgba(224,93,47,.16),transparent_35%),#0b0b0d] px-5 py-10"><div className="w-full max-w-md"><div className="mb-10 flex justify-center"><Logo /></div><div className="rounded-2xl border border-white/10 bg-card/80 p-7 shadow-2xl sm:p-9"><h1 className="text-2xl font-semibold">{register ? 'Create your account' : 'Welcome back'}</h1><p className="mt-2 text-sm text-muted-foreground">{register ? 'Start your cinematic journey today.' : 'Pick up where you left off.'}</p><form className="mt-7 flex flex-col gap-4" onSubmit={(e) => e.preventDefault()}>{register && <label className="text-sm">Full name<input className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-background px-3 outline-none focus:border-primary" placeholder="Jordan Davis" /></label>}<label className="text-sm">Email<input type="email" className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-background px-3 outline-none focus:border-primary" placeholder="you@example.com" /></label><label className="text-sm">Password<input type="password" className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-background px-3 outline-none focus:border-primary" placeholder="••••••••" /></label>{register && <label className="text-sm">Confirm password<input type="password" className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-background px-3 outline-none focus:border-primary" placeholder="••••••••" /></label>}{!register && <label className="flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" className="accent-primary" /> Remember me</label>}<Button className="mt-2 h-11 rounded-lg">{register ? 'Create account' : 'Sign in'}</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">{register ? 'Already a member?' : 'New to StreamFlix?'} <Link href={register ? '/login' : '/register'} className="font-medium text-primary hover:underline">{register ? 'Sign in' : 'Create an account'}</Link></p></div><Link href="/" className="mt-6 block text-center text-xs text-muted-foreground hover:text-foreground">← Back to StreamFlix</Link></div></main> }

export function ListToggle({ active = false }: { active?: boolean }) { const [saved, setSaved] = useState(active); return <Button variant="secondary" onClick={() => setSaved(!saved)} className="rounded-full bg-white/10 text-white hover:bg-white/15">{saved ? <Check data-icon="inline-start" /> : <Plus data-icon="inline-start" />}{saved ? 'In my list' : 'Add to my list'}</Button> }

export function ProfileMenu() { return <div className="flex items-center gap-4 rounded-2xl border border-white/10 bg-card p-5"><div className="grid size-14 place-items-center rounded-full bg-gradient-to-br from-primary to-orange-300 text-lg font-bold text-background">JD</div><div><p className="font-semibold">Jordan Davis</p><p className="text-sm text-muted-foreground">jordan@example.com</p></div><Link href="/profile" className="ml-auto rounded-lg p-2 text-muted-foreground hover:bg-white/5 hover:text-white"><User className="size-4" /></Link></div> }
